# Generated by Django 5.2.1 on 2025-05-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default='0', max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='calories',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='fat',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='protein',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='recipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='pages.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Main Course', 'Main Course'), ('Appetizers', 'Appetizers'), ('Dessert', 'Dessert')], default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='time',
            name='cook_time',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
        migrations.AddField(
            model_name='time',
            name='prepare_time',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6),
        ),
        migrations.AddField(
            model_name='time',
            name='recipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='pages.recipe'),
        ),
        migrations.AddField(
            model_name='time',
            name='total_time',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='pages.recipe'),
        ),
    ]
