# Generated by Django 5.2.1 on 2025-05-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ingredient_delete_ingredients_nutrition_calories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='time',
            old_name='prepare_time',
            new_name='prep_time',
        ),
        migrations.RemoveField(
            model_name='time',
            name='total_time',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
